FROM alpine
RUN apk update --no-cache && apk add --no-cache ca-certificates

ARG ENV
ARG SERVICE_NAME
ARG SERVICE_TYPE
ARG ROOT_PATH

ENV ENV=${ENV}
ENV SERVICE_NAME=${SERVICE_NAME}
ENV SERVICE_TYPE=${SERVICE_TYPE}
ENV ROOT_PATH=${ROOT_PATH}

ADD ${ROOT_PATH}/bin/ ${ROOT_PATH}/bin/
COPY ${ROOT_PATH}/etc/${ENV}-${SERVICE_NAME}-${SERVICE_TYPE}.yaml ${ROOT_PATH}/bin/
CMD ${ROOT_PATH}/bin/${ENV}-${SERVICE_NAME}-${SERVICE_TYPE} -f ${ROOT_PATH}/bin/${ENV}-${SERVICE_NAME}-${SERVICE_TYPE}.yaml