// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package tuser

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserinfoRequest struct {
	Userid               string   `protobuf:"bytes,1,opt,name=Userid,proto3" json:"Userid,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserinfoRequest) Reset()         { *m = UserinfoRequest{} }
func (m *UserinfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserinfoRequest) ProtoMessage()    {}
func (*UserinfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserinfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserinfoRequest.Unmarshal(m, b)
}
func (m *UserinfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserinfoRequest.Marshal(b, m, deterministic)
}
func (m *UserinfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserinfoRequest.Merge(m, src)
}
func (m *UserinfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserinfoRequest.Size(m)
}
func (m *UserinfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserinfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserinfoRequest proto.InternalMessageInfo

func (m *UserinfoRequest) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *UserinfoRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Response struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	AccessToken          string   `protobuf:"bytes,3,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	AccessExpire         int64    `protobuf:"varint,4,opt,name=accessExpire,proto3" json:"accessExpire,omitempty"`
	RefreshAfter         int64    `protobuf:"varint,5,opt,name=refreshAfter,proto3" json:"refreshAfter,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Response) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Response) GetAccessExpire() int64 {
	if m != nil {
		return m.AccessExpire
	}
	return 0
}

func (m *Response) GetRefreshAfter() int64 {
	if m != nil {
		return m.RefreshAfter
	}
	return 0
}

func (m *Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*RegisterRequest)(nil), "user.RegisterRequest")
	proto.RegisterType((*UserinfoRequest)(nil), "user.UserinfoRequest")
	proto.RegisterType((*Response)(nil), "user.Response")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x25, 0x6d, 0x1a, 0xf2, 0xcd, 0x57, 0x5a, 0x18, 0x54, 0x42, 0x4e, 0x25, 0x27, 0x41, 0x28,
	0xa8, 0x3f, 0x40, 0x3d, 0xf4, 0xe6, 0x41, 0x82, 0x9e, 0x25, 0xb6, 0x93, 0x1a, 0xb4, 0xd9, 0xb8,
	0x93, 0xa2, 0x7f, 0xc5, 0x3f, 0xe1, 0x6f, 0x94, 0x9d, 0xc9, 0x86, 0xb4, 0x78, 0xcb, 0x7b, 0xbb,
	0xef, 0xbd, 0x9d, 0x79, 0x01, 0xd8, 0x33, 0xd9, 0x65, 0x63, 0x4d, 0x6b, 0x30, 0x74, 0xdf, 0xd9,
	0x2d, 0x4c, 0xef, 0xcd, 0xb6, 0xaa, 0x73, 0xfa, 0xd8, 0x13, 0xb7, 0x78, 0x02, 0x13, 0xda, 0x15,
	0xd5, 0x7b, 0x12, 0x2c, 0x82, 0xf3, 0x7f, 0xb9, 0x02, 0x4c, 0x21, 0x6e, 0x0a, 0xe6, 0x4f, 0x63,
	0x37, 0xc9, 0x48, 0x0e, 0x7a, 0x9c, 0x3d, 0xc3, 0x3c, 0xa7, 0x6d, 0xc5, 0x2d, 0x59, 0x6f, 0x92,
	0x42, 0xfc, 0xc4, 0x64, 0xeb, 0x62, 0x47, 0x9d, 0x4f, 0x8f, 0x5d, 0xc0, 0x4a, 0x02, 0xd4, 0x47,
	0x81, 0x53, 0x3c, 0xf8, 0x80, 0xb1, 0x2a, 0x3c, 0xce, 0x6e, 0x60, 0xee, 0xd4, 0x55, 0x5d, 0x1a,
	0x1f, 0x70, 0x06, 0x91, 0x50, 0x9b, 0xce, 0xbe, 0x43, 0xce, 0xfc, 0xd1, 0xbc, 0x51, 0xed, 0xcd,
	0x05, 0x64, 0x3f, 0x01, 0xc4, 0x39, 0x71, 0x63, 0x6a, 0x26, 0x9c, 0xc1, 0xa8, 0x93, 0x8d, 0xf3,
	0x91, 0x4a, 0x68, 0xf8, 0x1e, 0x1d, 0x78, 0x01, 0xff, 0x8b, 0xf5, 0x9a, 0x98, 0xd5, 0x4e, 0x9f,
	0x34, 0xa4, 0x30, 0x83, 0xa9, 0xc2, 0xd5, 0x57, 0x53, 0x59, 0x4a, 0x42, 0x71, 0x3c, 0xe0, 0xdc,
	0x1d, 0x4b, 0xa5, 0x25, 0x7e, 0xbd, 0x2b, 0x5b, 0xb2, 0xc9, 0x44, 0xef, 0x0c, 0x39, 0x44, 0x08,
	0x65, 0x4f, 0x91, 0x44, 0xc8, 0xf7, 0xd5, 0x77, 0x00, 0xa1, 0x9b, 0x08, 0x2f, 0x60, 0x22, 0xed,
	0x20, 0x2e, 0xa5, 0xb9, 0x61, 0x55, 0xe9, 0x4c, 0xb9, 0x7e, 0xb2, 0x4b, 0x37, 0xa5, 0x16, 0x81,
	0xa7, 0xfe, 0xec, 0xa0, 0x98, 0xbf, 0x24, 0x7e, 0xb5, 0x5e, 0x72, 0xb4, 0xea, 0x63, 0xc9, 0x4b,
	0x24, 0x7f, 0xcf, 0xf5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc4, 0xef, 0xd2, 0xdb, 0x4b, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Response, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*Response, error)
	Userinfo(ctx context.Context, in *UserinfoRequest, opts ...grpc.CallOption) (*Response, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/user.User/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/user.User/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Userinfo(ctx context.Context, in *UserinfoRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/user.User/Userinfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	Login(context.Context, *LoginRequest) (*Response, error)
	Register(context.Context, *RegisterRequest) (*Response, error)
	Userinfo(context.Context, *UserinfoRequest) (*Response, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) Login(ctx context.Context, req *LoginRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserServer) Register(ctx context.Context, req *RegisterRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedUserServer) Userinfo(ctx context.Context, req *UserinfoRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Userinfo not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Userinfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserinfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Userinfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/Userinfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Userinfo(ctx, req.(*UserinfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _User_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _User_Register_Handler,
		},
		{
			MethodName: "Userinfo",
			Handler:    _User_Userinfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
