// Code generated by protoc-gen-go. DO NOT EDIT.
// source: point.proto

package point

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUserEarnRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PointId              int64    `protobuf:"varint,2,opt,name=PointId,proto3" json:"PointId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserEarnRequest) Reset()         { *m = GetUserEarnRequest{} }
func (m *GetUserEarnRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserEarnRequest) ProtoMessage()    {}
func (*GetUserEarnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbb1a16d5866e018, []int{0}
}

func (m *GetUserEarnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserEarnRequest.Unmarshal(m, b)
}
func (m *GetUserEarnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserEarnRequest.Marshal(b, m, deterministic)
}
func (m *GetUserEarnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserEarnRequest.Merge(m, src)
}
func (m *GetUserEarnRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserEarnRequest.Size(m)
}
func (m *GetUserEarnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserEarnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserEarnRequest proto.InternalMessageInfo

func (m *GetUserEarnRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserEarnRequest) GetPointId() int64 {
	if m != nil {
		return m.PointId
	}
	return 0
}

type GetUserEarnResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Point                int64    `protobuf:"varint,2,opt,name=Point,proto3" json:"Point,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	ExpiredAt            string   `protobuf:"bytes,4,opt,name=ExpiredAt,proto3" json:"ExpiredAt,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserEarnResponse) Reset()         { *m = GetUserEarnResponse{} }
func (m *GetUserEarnResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserEarnResponse) ProtoMessage()    {}
func (*GetUserEarnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbb1a16d5866e018, []int{1}
}

func (m *GetUserEarnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserEarnResponse.Unmarshal(m, b)
}
func (m *GetUserEarnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserEarnResponse.Marshal(b, m, deterministic)
}
func (m *GetUserEarnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserEarnResponse.Merge(m, src)
}
func (m *GetUserEarnResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserEarnResponse.Size(m)
}
func (m *GetUserEarnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserEarnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserEarnResponse proto.InternalMessageInfo

func (m *GetUserEarnResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserEarnResponse) GetPoint() int64 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *GetUserEarnResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetUserEarnResponse) GetExpiredAt() string {
	if m != nil {
		return m.ExpiredAt
	}
	return ""
}

func (m *GetUserEarnResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type GetUserUseRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PointId              int64    `protobuf:"varint,2,opt,name=PointId,proto3" json:"PointId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserUseRequest) Reset()         { *m = GetUserUseRequest{} }
func (m *GetUserUseRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserUseRequest) ProtoMessage()    {}
func (*GetUserUseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbb1a16d5866e018, []int{2}
}

func (m *GetUserUseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserUseRequest.Unmarshal(m, b)
}
func (m *GetUserUseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserUseRequest.Marshal(b, m, deterministic)
}
func (m *GetUserUseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserUseRequest.Merge(m, src)
}
func (m *GetUserUseRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserUseRequest.Size(m)
}
func (m *GetUserUseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserUseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserUseRequest proto.InternalMessageInfo

func (m *GetUserUseRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserUseRequest) GetPointId() int64 {
	if m != nil {
		return m.PointId
	}
	return 0
}

type GetUserUseResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Point                int64    `protobuf:"varint,2,opt,name=Point,proto3" json:"Point,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserUseResponse) Reset()         { *m = GetUserUseResponse{} }
func (m *GetUserUseResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserUseResponse) ProtoMessage()    {}
func (*GetUserUseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbb1a16d5866e018, []int{3}
}

func (m *GetUserUseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserUseResponse.Unmarshal(m, b)
}
func (m *GetUserUseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserUseResponse.Marshal(b, m, deterministic)
}
func (m *GetUserUseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserUseResponse.Merge(m, src)
}
func (m *GetUserUseResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserUseResponse.Size(m)
}
func (m *GetUserUseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserUseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserUseResponse proto.InternalMessageInfo

func (m *GetUserUseResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUserUseResponse) GetPoint() int64 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *GetUserUseResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetUserUseResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type GetUserPointRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserPointRequest) Reset()         { *m = GetUserPointRequest{} }
func (m *GetUserPointRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserPointRequest) ProtoMessage()    {}
func (*GetUserPointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbb1a16d5866e018, []int{4}
}

func (m *GetUserPointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserPointRequest.Unmarshal(m, b)
}
func (m *GetUserPointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserPointRequest.Marshal(b, m, deterministic)
}
func (m *GetUserPointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserPointRequest.Merge(m, src)
}
func (m *GetUserPointRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserPointRequest.Size(m)
}
func (m *GetUserPointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserPointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserPointRequest proto.InternalMessageInfo

func (m *GetUserPointRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetUserPointResponse struct {
	Point                int64    `protobuf:"varint,1,opt,name=Point,proto3" json:"Point,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserPointResponse) Reset()         { *m = GetUserPointResponse{} }
func (m *GetUserPointResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserPointResponse) ProtoMessage()    {}
func (*GetUserPointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbb1a16d5866e018, []int{5}
}

func (m *GetUserPointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserPointResponse.Unmarshal(m, b)
}
func (m *GetUserPointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserPointResponse.Marshal(b, m, deterministic)
}
func (m *GetUserPointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserPointResponse.Merge(m, src)
}
func (m *GetUserPointResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserPointResponse.Size(m)
}
func (m *GetUserPointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserPointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserPointResponse proto.InternalMessageInfo

func (m *GetUserPointResponse) GetPoint() int64 {
	if m != nil {
		return m.Point
	}
	return 0
}

func init() {
	proto.RegisterType((*GetUserEarnRequest)(nil), "point.GetUserEarnRequest")
	proto.RegisterType((*GetUserEarnResponse)(nil), "point.GetUserEarnResponse")
	proto.RegisterType((*GetUserUseRequest)(nil), "point.GetUserUseRequest")
	proto.RegisterType((*GetUserUseResponse)(nil), "point.GetUserUseResponse")
	proto.RegisterType((*GetUserPointRequest)(nil), "point.GetUserPointRequest")
	proto.RegisterType((*GetUserPointResponse)(nil), "point.GetUserPointResponse")
}

func init() { proto.RegisterFile("point.proto", fileDescriptor_dbb1a16d5866e018) }

var fileDescriptor_dbb1a16d5866e018 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x95, 0xd3, 0xa6, 0x25, 0x57, 0x09, 0x89, 0xa3, 0x42, 0x6e, 0x60, 0x88, 0x32, 0x75, 0x80,
	0x0e, 0xb0, 0x23, 0x55, 0x24, 0xa0, 0x6c, 0x28, 0x52, 0x7f, 0x40, 0x21, 0x1e, 0xb2, 0xc4, 0xc6,
	0x36, 0x12, 0xe2, 0x9f, 0xf0, 0xaf, 0xf8, 0x49, 0x28, 0x8e, 0xe3, 0x7c, 0x90, 0x09, 0x31, 0xde,
	0x7b, 0xbe, 0x77, 0xef, 0x9d, 0x0f, 0x56, 0x82, 0x97, 0x95, 0xde, 0x09, 0xc9, 0x35, 0x47, 0xdf,
	0x14, 0xf1, 0x23, 0xe0, 0x13, 0xd3, 0x07, 0xc5, 0x64, 0x7a, 0x94, 0x55, 0xce, 0xde, 0xde, 0x99,
	0xd2, 0x78, 0x01, 0x8b, 0x1a, 0xca, 0x0a, 0x4a, 0x22, 0xb2, 0x9d, 0xe5, 0xb6, 0x42, 0x0a, 0xcb,
	0xe7, 0xba, 0x2d, 0x2b, 0xa8, 0x67, 0x88, 0xb6, 0x8c, 0xbf, 0x08, 0x9c, 0x0f, 0x84, 0x94, 0xe0,
	0x95, 0x62, 0x78, 0x0a, 0x9e, 0x53, 0xf1, 0xb2, 0x02, 0xd7, 0xe0, 0x9b, 0x16, 0xdb, 0xdf, 0x14,
	0x18, 0xc1, 0x2a, 0x61, 0xea, 0x55, 0x96, 0x42, 0x97, 0xbc, 0xa2, 0xb3, 0x88, 0x6c, 0x83, 0xbc,
	0x0f, 0xe1, 0x15, 0x04, 0xe9, 0x87, 0x28, 0x25, 0x2b, 0xf6, 0x9a, 0xce, 0x0d, 0xdf, 0x01, 0x35,
	0xfb, 0x20, 0xd9, 0x51, 0x1b, 0xd6, 0x6f, 0x58, 0x07, 0xc4, 0x29, 0x9c, 0x59, 0x6b, 0x07, 0xc5,
	0xfe, 0x1e, 0xf1, 0xd3, 0xad, 0xca, 0xc8, 0xfc, 0x7f, 0xc0, 0x2e, 0xc2, 0x7c, 0x1c, 0xe1, 0xc6,
	0x6d, 0xd7, 0xe8, 0x8d, 0x43, 0x24, 0x83, 0x10, 0x49, 0x7c, 0x0d, 0xeb, 0xe1, 0x73, 0x6b, 0xd6,
	0x99, 0x23, 0x3d, 0x73, 0xb7, 0xdf, 0xc4, 0xc2, 0xb8, 0x87, 0x93, 0xf6, 0x07, 0x71, 0xb3, 0x6b,
	0xce, 0xe5, 0xf7, 0x79, 0x84, 0xe1, 0x14, 0x65, 0x47, 0xdc, 0xc3, 0xd2, 0xae, 0x08, 0xe9, 0xf0,
	0x59, 0xb7, 0xfc, 0x70, 0x33, 0xc1, 0xd8, 0xfe, 0x04, 0x02, 0xe7, 0x1b, 0x47, 0x83, 0xfa, 0xd9,
	0xc3, 0xcb, 0x49, 0xae, 0x51, 0x79, 0x59, 0x98, 0x23, 0xbf, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff,
	0x1d, 0xf3, 0x2a, 0x05, 0xf3, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PointClient is the client API for Point service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PointClient interface {
	UserEarn(ctx context.Context, in *GetUserEarnRequest, opts ...grpc.CallOption) (*GetUserEarnResponse, error)
	UserUse(ctx context.Context, in *GetUserUseRequest, opts ...grpc.CallOption) (*GetUserUseResponse, error)
	UserPoint(ctx context.Context, in *GetUserPointRequest, opts ...grpc.CallOption) (*GetUserPointResponse, error)
}

type pointClient struct {
	cc *grpc.ClientConn
}

func NewPointClient(cc *grpc.ClientConn) PointClient {
	return &pointClient{cc}
}

func (c *pointClient) UserEarn(ctx context.Context, in *GetUserEarnRequest, opts ...grpc.CallOption) (*GetUserEarnResponse, error) {
	out := new(GetUserEarnResponse)
	err := c.cc.Invoke(ctx, "/point.Point/UserEarn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointClient) UserUse(ctx context.Context, in *GetUserUseRequest, opts ...grpc.CallOption) (*GetUserUseResponse, error) {
	out := new(GetUserUseResponse)
	err := c.cc.Invoke(ctx, "/point.Point/UserUse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointClient) UserPoint(ctx context.Context, in *GetUserPointRequest, opts ...grpc.CallOption) (*GetUserPointResponse, error) {
	out := new(GetUserPointResponse)
	err := c.cc.Invoke(ctx, "/point.Point/UserPoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PointServer is the server API for Point service.
type PointServer interface {
	UserEarn(context.Context, *GetUserEarnRequest) (*GetUserEarnResponse, error)
	UserUse(context.Context, *GetUserUseRequest) (*GetUserUseResponse, error)
	UserPoint(context.Context, *GetUserPointRequest) (*GetUserPointResponse, error)
}

// UnimplementedPointServer can be embedded to have forward compatible implementations.
type UnimplementedPointServer struct {
}

func (*UnimplementedPointServer) UserEarn(ctx context.Context, req *GetUserEarnRequest) (*GetUserEarnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserEarn not implemented")
}
func (*UnimplementedPointServer) UserUse(ctx context.Context, req *GetUserUseRequest) (*GetUserUseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserUse not implemented")
}
func (*UnimplementedPointServer) UserPoint(ctx context.Context, req *GetUserPointRequest) (*GetUserPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserPoint not implemented")
}

func RegisterPointServer(s *grpc.Server, srv PointServer) {
	s.RegisterService(&_Point_serviceDesc, srv)
}

func _Point_UserEarn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserEarnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServer).UserEarn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/point.Point/UserEarn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServer).UserEarn(ctx, req.(*GetUserEarnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Point_UserUse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserUseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServer).UserUse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/point.Point/UserUse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServer).UserUse(ctx, req.(*GetUserUseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Point_UserPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServer).UserPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/point.Point/UserPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServer).UserPoint(ctx, req.(*GetUserPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Point_serviceDesc = grpc.ServiceDesc{
	ServiceName: "point.Point",
	HandlerType: (*PointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserEarn",
			Handler:    _Point_UserEarn_Handler,
		},
		{
			MethodName: "UserUse",
			Handler:    _Point_UserUse_Handler,
		},
		{
			MethodName: "UserPoint",
			Handler:    _Point_UserPoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "point.proto",
}
